wandb_version: 1

task:
  desc: null
  value: FlippingEnv-Beta
logdir:
  desc: null
  value: log
train_num:
  desc: null
  value: 10
test_num:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.0001
n_step:
  desc: null
  value: 1
target_update_freq:
  desc: null
  value: 100
buffer_size:
  desc: null
  value: 10000
batch_size:
  desc: null
  value: 64
eps_train:
  desc: null
  value: 1.0
eps_test:
  desc: null
  value: 0
epoch:
  desc: null
  value: 10000
step_per_epoch:
  desc: null
  value: 1000
step_per_collect:
  desc: null
  value: 1000
update_per_step:
  desc: null
  value: 0.1
prioritized_replay:
  desc: null
  value: true
alpha:
  desc: null
  value: 0.6
beta:
  desc: null
  value: 0.4
beta_final:
  desc: null
  value: 1.0
device:
  desc: null
  value: cpu
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721047005
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.11.9
      5: 0.17.4
      8:
      - 5
      9:
        2: tianshou
      13: linux-x86_64
